#!/usr/bin/env bash

BASE_PATH="$(dirname $0)/.."

source "$BASE_PATH/libexec/defaults"

export RONN_MANUAL="Deliver Manual"
export RONN_ORGANIZATION="Deliver $DELIVER_VERSION"

bundle exec ronn -w -s toc $BASE_PATH/man/*.ronn

unset RONN_MANUAL
unset RONN_ORGANIZATION
