.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DELIVER" "1" "August 2012" "Deliver 0.6.0-pre" "Deliver Manual"
.
.SH "NAME"
\fBdeliver\fR \- takes your code into production
.
.SH "SYNOPSIS"
\fBdeliver strategies\fR
.
.br
\fBdeliver check\fR
.
.br
\fBdeliver [\-s strategy]\fR
.
.br
.
.SH "DESCRIPTION"
Deliver is a pure bash deployment tool with virtually no dependencies\. It only cares about having enough info in the shell environment to do its job\. Why add Ruby or Python wrappers on top of system commands when bash was built for this?
.
.SH "STRATEGIES"
\fBdeliver strategies\fR will list all available strategies\. The default strategies make certain assumptions, but they are fully modular and customizable\.
.
.TP
\fBruby\fR
Foreman \fIhttps://github\.com/ddollar/foreman\fR\-aware, uses upstart by default\. Works seamlessly with rvm \fIhttps://rvm\.io/\fR\. \fIThis is the default strategy\fR
.
.TP
\fBnodejs\fR
Heavily inspired by the ruby strategy, also foreman\-aware, defaults to upstart\.
.
.TP
\fBgh\-pages\fR
How many times did you find yourself copying that rake task which generates and publishes to github:pages \fIhttp://pages\.github\.com/\fR your project\'s docco \fIhttps://github\.com/jashkenas/docco\fR or rocco \fIhttps://github\.com/rtomayko/rocco\fR? With deliver, just run \fBdeliver \-s gh\-pages\fR from the app\'s root path\.
.
.TP
\fBgenerated\fR
rocco \fIhttps://github\.com/rtomayko/rocco\fR, Jekyll \fIhttps://github\.com/mojombo/jekyll/\fR or even your own custom generator, everything goes\. Every deliver is a commit on the generated branch\. This then gets pushed out to all remote hosts (or just to github:pages)\.
.
.SH "CHECK"
\fBdeliver check\fR will ensure that everything is set up correctly\. You can also use this to see your final configuration\.
.
.SH "RUNNING MODES"
You can set a default mode via the MODE environment variable\. The running mode as a command option will always overwrite the MODE variable\.
.
.P
For example, you can have a \fBMODE=verbose\fR in your \fB\.deliver/config\fR file, but when running deliver with the \fB\-\-debug\fR option, the MODE for that one run will be \fIverbose\fR\.
.
.TP
\fB\-C\fR, \fB\-\-compact\fR (or \fBMODE=compact\fR)
Only shows the description and progress of each running task, regardless how many hosts it\'s running on\. Both standard and error output will be silenced\. \fIThis is the default mode\fR
.
.TP
\fB\-V\fR, \fB\-\-verbose\fR (or \fBMODE=verbose\fR)
Will not silence output of the running task\. Great for troubleshooting or getting feedback from all tasks\.
.
.TP
\fB\-D\fR, \fB\-\-debug\fR (or \fBMODE=debug\fR)
Runs the entire script in standard shell debug mode, shows every line of bash that gets executed along with the task output\. Well suited when writing your own strategies or customizing existing ones\.
.
.SH "COPYRIGHT"
Deliver is Copyright (C) 2012 Gerhard Lazu \fIhttp://twitter\.com/gerhardlazu\fR
