.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DELIVER" "1" "June 2012" "Deliver 1.0.0" "Deliver Manual"
.
.SH "NAME"
\fBdeliver\fR \- takes your code into production
.
.SH "SYNOPSIS"
\fBdeliver strategies\fR
.
.br
\fBdeliver check\fR
.
.br
\fBdeliver [\-s strategy]\fR
.
.br
.
.SH "DESCRIPTION"
Deliver is a pure bash deployment tool with virtually no dependencies\. It only cares about having enough info in the shell environment to do its job\. Why add Ruby or Python wrappers on top of system commands when bash was built for this one task?
.
.SH "STRATEGIES"
\fBdeliver strategies\fR will list all available strategies\. The default strategies make certain assumptions, but they are fully modular and customizable\.
.
.TP
\fBruby\fR
Foreman \fIhttps://github\.com/ddollar/foreman\fR\-aware, uses upstart by default\. Works seamlessly with rvm \fIhttps://rvm\.io/\fR\. \fIThis is the default strategy\fR
.
.TP
\fBnodejs\fR
Heavily inspired by the ruby strategy, also foreman\-aware, defaults to upstart\.
.
.TP
\fBgh\-pages\fR
How many times did you find yourself copying that rake task which generates and publishes to github:pages \fIhttp://pages\.github\.com/\fR your project\'s docco \fIhttps://github\.com/jashkenas/docco\fR or rocco \fIhttps://github\.com/rtomayko/rocco\fR? With deliver, just run \fBdeliver \-s gh\-pages\fR from the app\'s root path\.
.
.SS "Customizing a default strategy?"
.
.SS "Creating a new strategy?"
.
.SH "CHECK"
\fBdeliver check\fR will ensure that everything is set up correctly\. You can also use this to see your final configuration\.
.
.SH "RUNNING MODES"
You can set a default mode via the MODE environment variable\. The running mode as a command option will always overwrite the MODE variable\.
.
.P
For example, you can have a \fBMODE=verbose\fR in your \fB\.deliver/config\fR file, but when running deliver with the \fB\-\-debug\fR option, the MODE for that one run will be \fIverbose\fR\.
.
.TP
\fB\-C\fR, \fB\-\-compact\fR (or \fBMODE=compact\fR)
Only shows the description and progress of each running task, on a per\-host basis\. Both standard and error output will be silenced\. \fIThis is the default mode\fR
.
.TP
\fB\-V\fR, \fB\-\-verbose\fR (or \fBMODE=verbose\fR)
Will not silence output of the running task\. Great for troubleshooting or getting feedback from all tasks\.
.
.TP
\fB\-D\fR, \fB\-\-debug\fR (or \fBMODE=debug\fR)
Runs the entire script in standard shell debug mode, shows every line of bash that gets executed along with the task output\. Well suited when writing your own strategies or customizing existing ones\.
.
.TP
\fB\-T\fR, \fB\-\-test\fR (or \fBMODE=test\fR)
Similar to a dry\-run\. Will output each command that is going to run with no local or remote changes\. If you want full visibility into the final system commands that get generated, use this mode\.
.
.IP
If you want tighter control over your deployment process, you can have everyone on the team using the generated commands rather than using deliver directly\.
.
.SH "COPYRIGHT"
Deliver is Copyright (C) 2012 Gerhard Lazu \fIhttp://twitter\.com/gerhardlazu\fR
