#!/usr/bin/env bash


OPTIONAL_CONFIGS+=("CLEAN_DEPLOY")
OPTIONAL_CONFIGS+=("START_DEPLOY")

require_deploy_config
set_deploy_hosts

run() {
  authorize_hosts
  authorize_remote_hosts
  select_release_from_store "release"
  upload_release_archive
  [[ "$CLEAN_DEPLOY" = "true" ]] && remote_clean_release_dir
  remote_extract_release_archive
  [[ "$START_DEPLOY" = "true" ]] && force_start_release
}
