#!/usr/bin/env bash

REQUIRED_CONFIGS+=("APP")
REQUIRED_CONFIGS+=("BUILD_HOST")
REQUIRED_CONFIGS+=("BUILD_USER")
REQUIRED_CONFIGS+=("BUILD_AT")
OPTIONAL_CONFIGS+=("REBAR_CONFIG")

set_build_hosts

run() {
  authorize_hosts
  init_app_remotely
  git_push
  git_reset_remote
  git_clean_remote
  authorize_release_store_on_build_host
  erlang_get_and_update_deps
  erlang_clean_compile
  erlang_generate_release
  erlang_archive_release
  copy_release_to_release_store "release"
}



