#!/usr/bin/env bash

require_deploy_config
set_deploy_hosts

run() {
  authorize_hosts  
  authorize_remote_hosts 
  select_release_from_store
  upload_release_archive
  remote_extract_release_archive
}
