#!/usr/bin/env bash

REQUIRED_CONFIGS+=("APP")
REQUIRED_CONFIGS+=("HOSTS")
REQUIRED_CONFIGS+=("APP_USER")
REQUIRED_CONFIGS+=("DELIVER_TO")

run() {
  authorize_hosts  
  authorize_remote_hosts 
  install_release
}
