#!/usr/bin/env bash

REQUIRED_CONFIGS+=("APP")
REQUIRED_CONFIGS+=("HOSTS")
REQUIRED_CONFIGS+=("APP_USER")
REQUIRED_CONFIGS+=("DELIVER_TO")
OPTIONAL_CONFIGS+=("VERSION")

run() {
  authorize_hosts  
  authorize_remote_hosts 
  select_release_from_store
  upload_release_archive "/${APP}/releases"
  upgrade_release
}
