#!/usr/bin/env bash

REQUIRED_CONFIGS+=("APP")
REQUIRED_CONFIGS+=("BUILD_HOST")
REQUIRED_CONFIGS+=("BUILD_USER")
REQUIRED_CONFIGS+=("BUILD_AT")

set_build_hosts

run() {
  authorize_hosts  
  init_app_remotely
  git_push
  git_reset_remote 
  authorize_remote_hosts 
  rebar_clean_get_deps
  rebar_clean_compile
  rebar_renerate
  archive_release_dir
  copy_release_to_release_store
}



