#!/usr/bin/env bash

REQUIRED_CONFIGS+=("APP")
REQUIRED_CONFIGS+=("HOSTS")
REQUIRED_CONFIGS+=("APP_USER")
REQUIRED_CONFIGS+=("DELIVER_TO")

run() {
  authorize_hosts  
  authorize_remote_hosts 
  select_release_from_store
  upload_release_archive
  remote_extract_release_archive
}
