#!/usr/bin/env bash

REQUIRED_CONFIGS+=("APP")
REQUIRED_CONFIGS+=("NODE_ACTION")
REQUIRED_CONFIGS+=("NODE_ENVIRONMENT")


require_node_config

run() {
  status "${NODE_ACTION}ing servers"
  hint_message "executing action on nodes: $NODES"
  authorize_hosts  
}



