#!/usr/bin/env bash

# Pushes locally generated content to Github Pages.

STRATEGY_VARS="GH_PAGES_DIR"

if [ -z "$GH_PAGES_DIR" ]
then
  GH_PAGES_DIR="gh-pages"
fi

# This function must be present since deliver will call it directly
# Everything inside it or around it are only limited by your imagination : )
#
run() {
  __run 'is_clean'   "Checking local repository"
  __run 'ignore_generated_content' ""
  __run 'generate'  "Generating content"
  __run 'prepare'   "Preparing gh-pages branch"
  __run 'push'      "Pushing to github:pages"
  __run 'cleanup'   "Cleaning up"
}

# If working directory isn't clean, all changes will be lost
# We really DON'T want that
is_clean() {
  if [ $(git status | grep -c "working directory clean") = 0 ]
  then
    hint_message "\n\nYour working directory is not clean.
Either stash or commit before re-running this command.
I don't want you to lose any uncommitted changes, will stop here.
"
  fi
}

# If GH_PAGES_DIR is not ignored, it won't survive 'git clean -fd'
#
ignore_generated_content() {
  if [ $(egrep -c -e "^$GH_PAGES_DIR" .gitignore) = 0 ]
  then
    echo $GH_PAGES_DIR >> .gitignore
    __exec "git commit -a -m 'Ignoring content generated for github:pages'"
  fi
}

# If there is a local bin/generate executable, it will run it,
# otherwise it will default to the standard rocco command.
# 
#
generate() {
  local ghpages_cmd="$APP_ROOT/bin/gh-pages"

  if [ -x $ghpages_cmd ]
  then
    $ghpages_cmd
  else
    if [ ! -z "$ROCCO_FILES" ]
    then
      set -f # disables file globbing
      __exec "bundle exec rocco -o $GH_PAGES_DIR $ROCCO_FILES"
      set +f # enables file globbing
    fi
    __exec "cd $GH_PAGES_DIR"
    __exec "find . -type d -depth 1 | while read dir
            do
              mv $dir/* .
              rm -fr $dir
            done
            "
    if [ -e "$APP*.html" ]
    then
      __exec "mv $APP*.html index.html"
    fi
  fi
}

# Ensure that we have gh-pages branch,
# Prep the locally generated content
#
prepare() {
  __exec "git symbolic-ref HEAD refs/heads/gh-pages"
  __exec "rm .git/index"
  __exec "git clean -fd"
  mv $GH_PAGES_DIR/* .
  rm -fr $GH_PAGES_DIR
}

# Move all files from the generated folder into root folder,
# commit and push
#
push() {
  git add .
  if [[ ! $(git status) =~ "nothing to commit" ]]; then
    __exec "git commit -a -m 'Generated github:pages via deliver'"
    __exec "git push origin gh-pages"
  fi
}

cleanup() {
  __exec "git checkout -f master"
}
