#!/usr/bin/env bash

REQUIRED_CONFIGS+=("SERVERS")

run() {
  authorize_hosts
  init_app_remotely
  git_push
  git_reset_remote
  authorize_remote_hosts
  git_submodules
  npm_install
  foreman_export
  upstart
}
