#!/usr/bin/env bash

STRATEGY_VARS="APP_USER DELIVER_TO SERVERS"

run() {
  init_app_remotely &&
  git_push &&
  git_reset_remote &&
  git_submodules &&
  npm_install &&
  foreman_export &&
  upstart
}
