#!/usr/bin/env bash

REQUIRED_CONFIGS+=(HOSTS)
OPTIONAL_CONFIGS+=(OWNER GROUP PERMISSIONS)

run() {
  authorize_hosts
  init_app_remotely
  git_push
  git_reset_remote
  authorize_remote_hosts
  git_submodules
  permissions
}
