#!/usr/bin/env bash

APP="squirrel meets jekyll"   # used for the final success message
                              # Not really required

STRATEGY="gh-pages"           # This keeps the deliver command simple,
                              # otherwise you would have to run:
                              #
                              #     $ deliver gh-pages
                              #
                              # Arguments aren't working properly yet, will
                              # need to improve args parsing
                              #
                              # A local .deliver file would still need to be
                              # present though.
                              #
                              # Might remove this  requirement when proper guards
                              # will be in place
