#!/usr/bin/env bash

# Your app must run under this user. All files will be created as this user.
# The context in which deliver gets run must be able to login as this user,
# without asking for a password or a passphrase. The price of automation...
#
if [ -z "$APP_USER" ]
then
  APP_USER="$APP"
fi

# If your app runs under 'foobar' system user, the code will be delivered to
# '~foobar/app' by default. You can deliver multiple apps under the same user
# by overwriting this value on a per app basis, but I would discourage this practice.
# Each app should run under its own system user.
#
if [ -z "$DELIVER_TO" ]
then
  DELIVER_TO="~$APP_USER/app"
fi

# Configure which branch to push remotely
#
if [ -z "$BRANCH" ]
then
  BRANCH="master"
fi

# Ruby is the default deliver strategy.
# node.js might be hip, but Ruby is beautiful.
#
if [ -z "$STRATEGY" ]
then
  STRATEGY="ruby"
fi

__add_to_deprecations "REMOTE" "v0.6.0"
if [ -z "$REMOTE" ]
then
  REMOTE="$APP_USER@$SERVER"
fi

# Deliver used to be single-server, accounting for that here
#
SERVERS=$(__remote_friendly "$SERVER $SERVERS")
