#!/usr/bin/env bash

interpret_args() {
  debug
  verbose
  version
  capture_super_configs
}

# Run in verbose mode
#
verbose() {
  if [[ ! $ARGS =~ (-V|--verbose) ]]; then
    # silent mode (default)
    SILENCE="&> /dev/null"
  else
    # verbose mode
    VERBOSE=true
  fi
}

# Run in debug mode
#
debug() {
  if [[ $ARGS =~ (-D|--debug) ]]; then
    set -x
  fi
}

# Display the current version and exit
#
version() {
  if [[ $ARGS =~ (-v|--version) ]]; then
    echo -e "\n${txtbld}deliver v$VERSION$txtrst | $HOMEPAGE\n"
    exit 0
  fi
}

# Displays the available strategies and exits cleanly
# It can't be called in this context, strategies are loaded later on in the runtime
#
strategies() {
  if [[ $ARGS =~ (-s|--strategies) ]]; then
    list_strategies
    exit 0
  fi
}

# If STRATEGY or SERVER are specified at the time of invoking, hang onto them
# until we're ready to overwrite everything set from other sources
#
capture_super_configs() {
  SUPER_STRATEGY=$STRATEGY
  SUPER_SERVER=$SERVER
}
