#!/usr/bin/env bash

# When a `SIGINT` or `SIGTERM` is received, stop all background jobs and exit
# cheerfully.
# https://github.com/hecticjeff/shoreman/blob/master/shoreman.sh
# http://steve-parker.org/sh/trap.shtml
#
__graceful_stop() {
  local _message="Stopping deliver..."
  hint_message "\n$_message" &&
  __log "$_message" &&
  kill ${background_jobs_pids[*]} 2>&1 &&
  local _message="DELIVER STOPPED!"
  success_message "\n$_message\n" &&
  __log "$_message" &&
  __log "===========================================================" &&
  exit 0
}

# Ensures args (in this case hosts) are space separated so that we can easily loop over them
# e.g. " ruby-1,ruby-2 " -> "ruby-1 ruby-2"
#
__remote_friendly() {
  echo "$@" | tr ',' ' ' | sed 's/^ //' | sed 's/ $//'
}

# If these values are specified at the runtime, hang onto them
# until we're ready to overwrite everything set from other sources
#
__capture_runtime_configs() {
  RUNTIME_STRATEGY="$STRATEGY"
  RUNTIME_BRANCH="$BRANCH"
  RUNTIME_SERVERS="$(__remote_friendly "$SERVER $SERVERS")"
}

# If STRATEGY or SERVERS are specified at the time of invoking, overwrite
# anything that has been set from other sources
#
__apply_runtime_configs() {
  if [ -n "$RUNTIME_STRATEGY" ]
  then
    STRATEGY="$RUNTIME_STRATEGY"
  fi

  if [ -n "$RUNTIME_BRANCH" ]
  then
    BRANCH="$RUNTIME_BRANCH"
  fi

  if [ -n "$RUNTIME_SERVERS" ]
  then
    SERVERS="$RUNTIME_SERVERS"
  fi
}

# Loads the .deliver config file if it exists
# This is now optional. All config values can be passed at runtime, or, even
# better you can create a project-specific deploy (or even cap deploy) which is
# just a function calling deliver behind the scenes. Imagine the following:
#
#   deploy() {
#     APP=awesome SERVER=ruby-1 PORT=5000 deliver
#   }
#
__load_app_config() {
  if [ -f "$APP_CONFIG" ]
  then
    source "$APP_CONFIG"
  fi
}

# Ensures all required configs are set, tries to be helpful by adding some
# sane defaults
#
__default_app_config() {
  source "$BASE_PATH/libexec/app_config"
}

# Builds an index of all available strategies
#
__find_all_strategies() {
  local strategies_path=()

  # There are strategies that came with deliver itself
  if [ -d "$BASE_PATH/strategies" ]; then
    strategies_path+=("$BASE_PATH/strategies")
  fi
  # Per-project strategies
  if [ -d "$APP_ROOT/.deliver/strategies" ]; then
    strategies_path+=("$APP_ROOT/.deliver/strategies")
  fi

  STRATEGIES=$(find "${strategies_path[@]}" -regex '^[a-zA-Z0-9/.-]*$' -type f ! -iname 'readme*')
  for strategy in $STRATEGIES
  do
    STRATEGIES_NAME="$STRATEGIES_NAME ${strategy##*/}"
  done
}

# Load the correct strategy
#
__load_strategy() {
  for strategy in $STRATEGIES
  do
    [[ ! $strategy =~ $STRATEGY ]] && continue
    source "$strategy" && strategy_loaded=true && break
  done

  if [ -z "$strategy_loaded" ]
  then
    error_message "\n'$STRATEGY' strategy does not exist"
    __available_strategies
    exit 1
  fi
}

# Appends app user to all hosts so that we can log in with this user
# on specific remote jobs. Formats all servers in a format parallel can work with.
#
__remote_hosts() {
  for server in $SERVERS
  do
    SERVERS_APP_USER="$SERVERS_APP_USER,$APP_USER@$server"
  done
  SERVERS="$(__remote_friendly $SERVERS)"
  SERVERS_APP_USER="$(__remote_friendly $SERVERS_APP_USER)"
}

__check_config() {
  set -f # disables file globbing
  local _configs=("$REQUIRED_VARS $STRATEGY_VARS")
  local _missing_configs=()

  echo ""

  for config in $_configs
  do
    local _config_value="$(echo $(eval echo \$$config))"
    if [ -z "$_config_value" ]
    then
      _missing_configs+=("$config")
      local _config_text="${txtred}"
      local _check_failed=true
    else
      local _config_text="${txtgrn}"
    fi
    # http://unstableme.blogspot.co.uk/2009/07/text-alignment-with-awk-printf-function.html
    # http://linuxconfig.org/bash-printf-syntax-basics-with-examples
    # http://stackoverflow.com/questions/6345429/how-do-i-print-some-text-in-bash-and-pad-it-with-spaces-to-a-certain-width
    # http://wiki.bash-hackers.org/commands/builtin/printf
    test -n "$CHECK" && printf "%-20s\t%s\n" "${_config_text}$config" "$_config_value${txtrst}"
  done
  set +f # re-enables file globbing

  if [ -n "$_check_failed" ]
  then
    echo -e "\n${bldred}DELIVER IS MISSING THE FOLLOWING CONFIG(S):${txtrst}\n\n${txtred}${_missing_configs[@]}${txtrst}\n"
    exit 1
  else
    test -n "$CHECK" && echo -e "\n${bldgrn}READY TO DELIVER!${txtrst}\n" && exit 0
  fi
}

# Mode aware:
# * COMPACT - silences jobs
# * TEST - captures all jobs, no local or remote changes
#
__exec() {
  eval "$1 $SILENCE"
}

# Waits until all background jobs finish successfully
# If any of them fail, the entire script fails
#
__monitor_background_jobs() {
  for (( i = 0 ; i < ${#background_jobs_pids[@]} ; i++ ))
  do
    wait ${background_jobs_pids[$i]}
    local _exit_status="$?"
    if [[ "$_exit_status" != 0 ]]
    then
      error "\nFAILED $stopping $_exit_status:\n${background_jobs[$i]}\n"
    fi
  done

  unset background_jobs_pids
  unset background_jobs
}

# Runs commands in parallel, as background jobs
#
__parallelize() {
  local _job="$1"
  local _hosts="${2:-"$SERVERS_APP_USER"}"

  background_job_pids=()
  background_jobs=()

  for _host in $_hosts
  do
    local _logged_job="$(eval echo $_job)"
    if [[ $MODE = "verbose" ]]
    then
      echo "$_logged_job"
    fi

    ( eval "$_job" ) &
    # WON'T WORK because it captures eval's pid, not the job's pid
    # Ideally, I want to stay away from eval
    background_job_pids+=("$!")
    background_jobs+=("$_logged_job")
  done

  __monitor_background_jobs
}

# Multi-host & mode aware
#
__remote() {
  local _remote_job="$1"

  #__parallelize "ssh -o ConnectTimeout=$SSH_TIMEOUT \"\$_host\" \"$_remote_job\""

  if [[ $MODE != "test" ]]
  then
    local _remote_job="$1"
    local _hosts="${2:-"$SERVERS_APP_USER"}"
    background_jobs_pids=()
    background_jobs=()

    __log "${_hosts} : $_remote_job"

    for _host in $_hosts
    do
      ssh -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job $SILENCE" &
      background_jobs_pids+=("$!")
      local _background_job="ssh -o ConnectTimeout=$SSH_TIMEOUT $_host $_remote_job $SILENCE"
      #__log "BACKGROUND JOB: $_background_job"
      background_jobs+=("$_background_job")
    done

    #__log "REMOTE PIDS: ${background_jobs_pids[@]}"

    __monitor_background_jobs
  fi
}

# Logs all events (including formatting styles) so that people can tail,
# inspect and use for general debugging.
#
__log() {
  local _line="$(date) ::: $@"

  echo "$_line" >> $log_file
}
