#!/usr/bin/env bash

VERSION="0.6.0"
HOMEPAGE="https://github.com/gerhard/deliver"
CREATOR="Gerhard Lazu"

ARGS="$@"

ORIGIN_DIR="$(pwd)"
__add_to_deprecations "APP_ROOT" "v0.7.0"
APP_ROOT="$ORIGIN_DIR"

APP_CONFIG="$ORIGIN_DIR/.deliver/config"

GIT_REMOTE="deliver"
__add_to_deprecations "DELIVER_REMOTE" "v0.7.0"
DELIVER_REMOTE="$GIT_REMOTE"

SSH_TIMEOUT=3

# Sincer deliver leverages foreman,
# it supports all the supervisors that foreman does
SUPERVISOR="upstart"

AUTHORIZED_REMOTE_HOSTS=()

REQUIRED_CONFIGS=("ORIGIN_DIR" "STRATEGY")
OPTIONAL_CONFIGS=("APP" "APP_USER" "DELIVER_TO" "BRANCH" "SUPERVISOR" "FOREMAN_EXTRAS" "PORT" "AUTHORIZED_REMOTE_HOSTS")

MODE="compact"

log_file="/tmp/deliver-${APP}"
