#!/usr/bin/env bash

VERSION="1.0.0"
HOMEPAGE="https://github.com/gerhard/deliver"
CREATOR="Gerhard Lazu"

ARGS=$@

APP_ROOT=$(pwd)
APP=$(basename $APP_ROOT)
APP_CONFIG="$APP_ROOT/.deliver/config"

GIT_REMOTE="deliver"
DELIVER_REMOTE=$GIT_REMOTE # legacy

REQUIRED_VARS="APP APP_ROOT STRATEGY"

MODE="compact"
