#!/usr/bin/env bash

# sets the build host, user and path as deliver hosts and path
set_build_hosts() {
  # use build host and user for remote operations
  export HOSTS=$BUILD_HOST 
  export APP_USER=$BUILD_USER
  # use deliver to as built at destination
  export DELIVER_TO=$BUILD_AT  
}


rebar_clean_get_deps() {
  __exec_if_defined "pre_rebar_clean_get_deps"

  status "Fetching rebar dependencies"
  __remote "
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd $DELIVER_TO $SILENCE
    ./rebar -k delete-deps $SILENCE
    ./rebar get-deps $SILENCE
  "

  __exec_if_defined "post_rebar_clean_get_deps"
}

rebar_clean_compile() {
  __exec_if_defined "pre_rebar_clean_compile"

  status "Compiling sources"
  __remote "
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd $DELIVER_TO $SILENCE
    ./rebar clean compile $SILENCE
  "

  __exec_if_defined "post_rebar_clean_compile"
}

rebar_renerate() {
  __exec_if_defined "pre_rebar_renerate"

  status "Generating release"
  __remote "
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd $DELIVER_TO $SILENCE
    ./rebar -f generate $SILENCE
  "

  __exec_if_defined "post_rebar_renerate"
}
