#!/usr/bin/env bash

__version() {
  echo -e "\n${txtbld}deliver v$VERSION${txtrst} | $HOMEPAGE\n"
}

__help() {
  __version
  echo -e "  Deliver takes your local code and sets it up in production. A
  cross between Capistrano, git-deploy and heroku deploys, but language
  agnostic.

${txtbld}USAGE${txtrst}

    deliver [options] [strategy]

  With no options, it will run in compact mode and will pick up the
  strategy from your .deliver/config file. If you don't define a strategy,
  it will use the ruby one by default.

  You can also specify a runtime strategy which will overwrite any
  subsequent configs:

    STRATEGY=gh-pages deliver

  This will use the gh-pages strategy, regardless of what you have
  defined in your .deliver/config file. Equally, a STRATEGY env variable
  will overwrite all subsequent values (except the runtime strategy).

${txtbld}OPTIONS${txtrst}

  -v, --version     Shows the version and exits.

  -h, --help        Shows this help.

  -s, --strategies  Lists all available strategies.

  -V, --verbose     Will not silence the output of any commands. Great
                    for troubleshooting or understanding what is
                    actually happening behind the scenes.

  -D, --debug       Runs the entire script in standard bash debug mode.
"
}

while (( "$#" )); do
  arg="$1"; shift

  case "$arg" in
    "-D" | "--debug")
      set -x ;;
    "-V" | "--verbose")
      VERBOSE=true
      SILENCE="" ;;
    "-h" | "--help")
      __help
      exit 0 ;;
    "-v" | "--version")
      __version
      exit 0 ;;
    *) # ignore everything else
      true ;;
  esac
done
