#!/usr/bin/env bash

base_path="$( cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd )"

source "$base_path/libexec/defaults"

export RONN_MANUAL="Deliver Manual"
export RONN_ORGANIZATION="Deliver $VERSION"

bundle exec ronn -w -s toc $base_path/share/man/*.ronn
mv $base_path/share/man/deliver.1 $base_path/share/man/man1/

unset RONN_MANUAL
unset RONN_ORGANIZATION
